### ISSUE TITLE
Feature: limit retention of the lock history

### ISSUE THREAD

**Issue by schlitzered** [dm-drogeriemarkt/foreman_dlm#14]
Hello,

it would be nice to limit the retention of history of a lock. i am talking about what you can see in these URLS:

https://foreman.example.com/foreman_dlm/dlmlocks/$LOCK_INDEX

**Comment by schlitzered** [comment]
i guess over time the data of which host acquired/released a lock will pile up in the database.

so it would be nice if limits could be implemented, like:
- only keep 10k log messages per lock
- remove log messages older then 7 days

**Comment by timogoebel** [comment]
These logs should be removed together with the audit logs. But I see that it might be a good idea to store them somewhere else.
