### ISSUE TITLE
Promotion: foreman_dlm_updater

### ISSUE THREAD

**Issue by schlitzered** [dm-drogeriemarkt/foreman_dlm#15]
Hello,

i have created a python based tool to act as a Linux/Unix system counterpart to this awesome plugin.

do you might like to show it some love, and add it to your readme?

here is a link to the tool:   https://github.com/schlitzered/foreman_dlm_updater

the script itself should work on all linux/unix like operating systems, and can be installed via pip3.

the logic to check if an updated is needed, or how to install upgrades, has to be implemented in separate scripts.

foreman_dlm_updater more or less only offers a workflow implementation on how to perform updates, including the dlm lock handling.

Kind Regards

**Comment by timogoebel** [comment]
@schlitzered: Thanks, this is awesome. I'll definitely enhance the README with a link to `foreman_dlm_updater`.
