### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by schlitzered** [dm-drogeriemarkt/foreman_dlm#39]
Hello, are there any plans to have a new release with the latest changes, i would also live the test an Release Candidate.

**Comment by timogoebel** [comment]
@schlitzered: I have created a milestone 1.1.0 on Github and assigned the issues we want to work on before we do an actual release. I don't have an ETA, unfortunately, but it should not be too long.

**Comment by timogoebel** [comment]
I believe the question was answered. Closing this for now.
